### ISSUE TITLE
Modeling a HP Steam generator with TESPY

### ISSUE THREAD

**Issue by ibuzzo** [fwitte/chp_orc#1]
I am trying to model a high pressure steam drum from a water tube boiler, in which the saturated liquid (out1) flows into an evaporator and then back into the drum as saturated steam (in2).

![HP drum](https://github.com/fwitte/chp_orc/assets/152515112/26801783-ea93-4db7-8824-b2a26f689fdb)

Is it actually possible to recreate this connection using tespy component "Drum" ?  When trying, the program shows the following error:

![image](https://github.com/fwitte/chp_orc/assets/152515112/7c1ecc30-6ad1-4283-b45a-fecfcad587f0)

**Comment by fwitte** [comment]
Hi @ibuzzo,

could you attach a minimal code example to reproduce the issue? The drum component would be the one you are searching for, so I guess there is an issue in your model.

Thank you

**Comment by fwitte** [comment]
Please open a discussion on the oemof/tespy repository, thanks
